# services:
#   img:
#     build: .
#     container_name: basic-container
#     ports: 
#       - 3000:3000

#

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-image-name
