
# Use an official Node.js runtime as the base image
FROM node:latest

# Install NGINX
RUN apt-get update && \
    apt-get install -y nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the working directory in the container
WORKDIR /src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose port 80 for NGINX
EXPOSE 80

# Copy NGINX configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Start NGINX and your Node.js application
CMD service nginx start && npm start






# FROM node:latest
# WORKDIR /src/app
# COPY package*.json ./
# RUN npm install
# COPY . . 
# RUN npm run build
# EXPOSE 3000
# CMD [ "npm", "start" ]