# Build stage
FROM node:latest AS build
WORKDIR /src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /src/app /usr/share/nginx/html
COPY deployment_app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]




# FROM node:latest
# WORKDIR /src/app
# COPY package*.json ./
# RUN npm install
# COPY . . 
# RUN npm run build
# EXPOSE 3000
# CMD [ "npm", "start" ]