name: Deploy

# Trigger the workflow on
# pull request events on the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.57.87
          username: root
          port: 22
          key: ${{ secrets.SSHKEY2 }}
          script: |
            docker pull rishabh007dubey/test-docker-image-upload
            docker run -d -p 3005:3000 rishabh007dubey/test-docker-image-upload
