name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub s
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull rishabh007dubey/test-docker-image-upload

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.57.87
          username: root
          port: 22
          key: ${{ secrets.SSHKEY2 }}
          script: |
            docker stop testonport80 || true
            docker rm testonport80 || true
            docker run -d --name testonport80 -p 80:3000 rishabh007dubey/test-docker-image-upload
