name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-docker-username/your-image-name:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push your-docker-username/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to server via SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Pull Docker image on server
        run: ssh username@hostname "docker pull your-docker-username/your-image-name:latest"

      - name: Run Docker container on server
        run: ssh username@hostname "docker run -d --name your-container-name -p 80:3000 your-docker-username/your-image-name:latest"
