name: Docker Build and Deploy

on:
  #workflow_dispatch:  # This will trigger the workflow manually
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag with timestamp
        id: tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }} deployment_app

      - name: Push Docker image
        run: docker push rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.57.87
          username: root
          port: 22
          key: ${{ secrets.SSHKEY2 }}
          script: |
            docker pull rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}
            docker stop demo-app || true
            docker rm demo-app || true
            docker run -d --name demo-app -p 80:3000 rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}
