name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag with timestamp
        id: tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }} deployment_app

      - name: Push Docker image
        run: docker push rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d --name your_container_name -p 80:80 rishabh007dubey/test-docker-image-upload:${{ env.IMAGE_TAG }}
